name = "PathTracing"
uuid = "73009a29-908e-45e1-a031-5649e29e4d77"
authors = ["Chris Foster <chris42f@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
